language: python
dist: trusty
notifications:
  email: false
python:
  - 3.6
env:
  - AWS_DEFAULT_REGION=us-west-2 BOTO_CONFIG=/dev/null AWS_XRAY_SDK_ENABLED=false
before_install:
  - pip install boto
  - pip install boto3
  - pip install flake8
  - pip install faker
  - flake8 gsuite_driver
  - npm install -g dynalite
install:
  - pip install -r gsuite_driver/requirements.txt
  - scripts/start-dynamo-local.sh
script:
  - python3 -m unittest discover tests
